## Reporting Insights

#### Inspection:
### 1. Taxonomy gap analysis:

### Goal: “What kinds of user needs appear in the text that are not covered by my current intent list?”
   - Inspect “unknown” intent messages (missing intents)
   - Inspect intent missmatch
### 2. Overlapping intent analysis:

### Goal: “Where do my existing intents blur into each other and confuse the model/business?”
   - Inspect intent overlapping

### 3. Provide Recommendations
   -

In [3]:
#Load dataset
import pandas as pd
Inspect intent overlapping
df = pd.read_csv("../data/twcs_intent_simulated.csv")
df_convo_analysis = pd.read_csv("../data/twcs_multiturn_sample.csv")
df_convo_analysis.head()

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id,response_list,conversation_id,intent,confidence,is_low_conf,is_fallback,is_user,is_company
0,192624,161253,True,Wed Oct 04 13:59:33 +0000 2017,@161252 What's that egg website people talk about,192623,192625.0,[192623],192626.0,refund_request,0.587868,True,True,True,False
1,738238,296574,True,Fri Oct 06 18:29:06 +0000 2017,Why!🤷🏻‍♀️ #iOS11 @AppleSupport https://t.co/BX...,738237,NaN,[738237],738238.0,unknown,0.579054,True,True,True,False
2,2414302,AppleSupport,False,Tue Nov 14 17:38:01 +0000 2017,@693975 We can assist you. We recommend updati...,2414303,2414304.0,[2414303],2414304.0,billing_issue,0.605361,False,False,False,True
3,1793929,539096,True,Thu Oct 12 06:04:41 +0000 2017,@331912 @115955 Thats better than having an un...,1793928,1793930.0,[1793928],1793933.0,order_status,0.984484,False,False,True,False
4,2088018,617376,True,Mon Nov 06 20:30:49 +0000 2017,@VirginAmerica is probably one of the best air...,2088017,NaN,[2088017],2088018.0,technical_problem,0.735044,False,False,True,False

In [4]:
df.head()

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id,Clean_text,conversation_id,text_lemma,intent,confidence,is_low_conf,is_fallback,is_user,is_company
0,192624,161253,True,Wed Oct 04 13:59:33 +0000 2017,@161252 What's that egg website people talk about,192623,192625.0,what s that egg website people talk about,192625.0,s egg website people talk,refund_request,0.631970,False,False,True,False
1,738238,296574,True,Fri Oct 06 18:29:06 +0000 2017,Why!🤷🏻‍♀️ #iOS11 @AppleSupport https://t.co/BX...,738237,NaN,why,738238.0,NaN,technical_problem,0.682013,False,False,True,False
2,2414302,AppleSupport,False,Tue Nov 14 17:38:01 +0000 2017,@693975 We can assist you. We recommend updati...,2414303,2414304.0,we can assist you we recommend updating to ios...,2414304.0,assist recommend update io 11 1 1 haven t chan...,account_access,0.891190,False,False,False,True
3,1793929,539096,True,Thu Oct 12 06:04:41 +0000 2017,@331912 @115955 Thats better than having an un...,1793928,1793930.0,thats better than having an unstable connectio...,1793930.0,s well have unstable connection drop 5 20 min,technical_problem,0.433034,True,True,True,False
4,2088018,617376,True,Mon Nov 06 20:30:49 +0000 2017,@VirginAmerica is probably one of the best air...,2088017,NaN,is probably one of the best airlines i ve ever...,2088018.0,probably good airline ve experience,refund_request,0.427244,True,True,True,False

### 1. Inspect “unknown” intent messages (taxonomy gaps)

In [12]:
sorted(df["intent"].unique())

['account_access',
 'billing_issue',
 'general_query',
 'order_status',
 'refund_request',
 'smalltalk',
 'technical_problem',
 'unknown']

In [6]:
unknown_df = df['intent'] == 'unknown'
unknown_df.value_counts()

intent
False    4368
True      632
Name: count, dtype: int64

### 1.1 : Get 50 unknow intent samples

In [9]:
df_unknown = df[unknown_df]
df_unknown

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id,Clean_text,conversation_id,text_lemma,intent,confidence,is_low_conf,is_fallback,is_user,is_company
7,2206333,645101,True,Fri Nov 10 00:12:30 +0000 2017,@Uber_Support Reports are there are 68 Ubers w...,2206335,2206332.0,reports are there are 68 ubers waiting for pas...,2206332.0,report 68 uber wait passenger isn t work,unknown,0.939616,False,True,True,False
9,2744170,162033,True,Mon Nov 20 19:15:58 +0000 2017,@AmazonHelp Saw that but only after a labored ...,NaN,2744169.0,saw that but only after a labored hunt bigger ...,2744169.0,see labored hunt big point usb 2 0 expect expl...,unknown,0.746737,False,True,True,False
17,1820869,ChipotleTweets,False,Sun Oct 29 00:45:00 +0000 2017,@546646 also Guactober. Sounds like a good tim...,NaN,1820870.0,also guactober sounds like a good time to make...,1820870.0,guactober sound like good time wish shawn,unknown,0.540705,True,True,False,True
29,647159,Tesco,False,Wed Nov 22 18:35:26 +0000 2017,"@273717 Hi, I'm sorry the Finest pulled pork i...",NaN,647158.0,hi i m sorry the finest pulled pork is tough a...,647158.0,hi m sorry fine pulled pork tough inconvenienc...,unknown,0.943423,False,True,False,True
39,872288,294899,True,Sat Oct 14 12:02:43 +0000 2017,@AmazonHelp you don't need access to my accoun...,872289,872286.0,you don t need access to my account i just wan...,872286.0,don t need access account want know prime memb...,unknown,0.736718,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4961,496426,SouthwestAir,False,Fri Dec 01 18:10:59 +0000 2017,@233436 Hi there! Our creamers are lactose-fre...,496427,496428.0,hi there our creamers are lactose free gluten ...,496428.0,hi creamer lactose free gluten free kosher dai...,unknown,0.613503,False,True,False,True
4967,2084262,594228,True,Sun Nov 05 23:26:29 +0000 2017,@KeyBank_Help I sent an email on Thursday. As ...,NaN,2084261.0,i sent an email on thursday as of today i have...,2084261.0,send email thursday today response whatsoever,unknown,0.449828,True,True,True,False
4990,2456155,AppleSupport,False,Wed Nov 15 04:26:00 +0000 2017,@703576 We'd like to gather some more informat...,NaN,2456156.0,we d like to gather some more information for ...,2456156.0,d like gather information well troubleshooting...,unknown,0.535039,True,True,False,True
4992,1771166,532409,True,Fri Jul 21 14:24:46 +0000 2017,@YahooCare hi I can't recover my password. My...,1771165,NaN,hi i can t recover my password my recovery ema...,1771166.0,hi t recover password recovery email hotmail d...,unknown,0.407792,True,True,True,False
4997,1116094,383370,True,Tue Oct 24 03:35:27 +0000 2017,.@XboxSupport: the new #XboxOne update appears...,1116093,NaN,the new update appears to have bricked my cons...,1116094.0,new update appear bricke console finish apply ...,unknown,0.967052,False,True,True,False

In [10]:
df_unknown_sample = df_unknown.sample(50, random_state=42)
df_unknown_sample

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id,Clean_text,conversation_id,text_lemma,intent,confidence,is_low_conf,is_fallback,is_user,is_company
2614,1710970,518307,True,Tue Nov 07 01:32:37 +0000 2017,@SpotifyCares Hello. My payment for premium ac...,1710969,NaN,hello my payment for premium account was succe...,1710970.0,hello payment premium account succee free acco...,unknown,0.460524,True,True,True,False
2009,2884812,Safaricom_Care,False,Tue Nov 28 11:37:28 +0000 2017,@220140 Kindly DM these details as you are sha...,NaN,2884810.0,kindly dm these details as you are sharing sen...,2884810.0,kindly dm detail share sensitive info public e...,unknown,0.779293,False,True,False,True
4598,2877696,798770,True,Tue Nov 28 07:46:47 +0000 2017,@AmazonHelp Got the same messag from https://t...,NaN,2877695.0,got the same messag from please add pakistan i...,2877695.0,get messag add pakistan shipping list country ...,unknown,0.705050,False,True,True,False
1205,633688,McDonalds,False,Wed Oct 04 19:08:29 +0000 2017,@270205 On a real note: Who's going to step up...,"633689,633690",633691.0,on a real note who s going to step up and help...,633691.0,real note s go step help friend swing,unknown,0.665190,False,True,False,True
4023,370156,203666,True,Sun Nov 05 23:13:53 +0000 2017,@TMobileHelp @203665 Plus it looks like ZERO m...,NaN,370155.0,plus it looks like zero mainstream devices sup...,370155.0,plus look like zero mainstream device support ...,unknown,0.920976,False,True,True,False
3283,2131068,SouthwestAir,False,Wed Nov 08 19:18:59 +0000 2017,"@141013 Hi, Meg! It sounds like you applied fu...",2131067,2131069.0,hi meg it sounds like you applied funds to boo...,2131069.0,hi meg sound like apply fund book reservation ...,unknown,0.590493,True,True,False,True
1349,747890,AmericanAir,False,Wed Oct 11 17:23:46 +0000 2017,@298780 We're happy to check on the status for...,"747891,747892,747893",747887.0,we re happy to check on the status for you ple...,747887.0,happy check status follow dm record locator s go,unknown,0.561656,True,True,False,True
595,2273281,661267,True,Sat Nov 11 11:25:59 +0000 2017,@AmazonHelp Si esta todo correcto es vendido y...,2273280,2273282.0,si esta todo correcto es vendido y gestionado ...,2273282.0,si esta todo correcto es vendido y gestionado ...,unknown,0.910647,False,True,True,False
4339,2049771,MOO,False,Wed Nov 01 09:12:11 +0000 2017,@500591 No problem!,NaN,2049772.0,no problem,2049772.0,problem,unknown,0.534412,True,True,False,True
1335,2715777,ATVIAssist,False,Mon Nov 20 05:35:09 +0000 2017,"@762342 Apologies for the delay, we are active...",NaN,2715778.0,apologies for the delay we are actively workin...,2715778.0,apology delay actively work resolve server iss...,unknown,0.479986,True,True,False,True
2194,1980776,AppleSupport,False,Tue Oct 31 22:48:00 +0000 2017,@586340 Thanks for reaching out. What's the ex...,NaN,9204.0,thanks for reaching out what s the exact ios y...,9204.0,thank reach s exact io currently have issue le...,unknown,0.738590,False,True,False,True
223,771275,AsurionCares,False,Wed Oct 11 23:02:39 +0000 2017,@304206 We'll be glad to assist you. Can you p...,NaN,771276.0,we ll be glad to assist you can you please dm ...,771276.0,ll glad assist dm carrier claim mobile number kf,unknown,0.967638,False,True,False,True
406,1901295,400382,True,Tue Oct 24 00:26:17 +0000 2017,So happy that #Simpsons #Treehouseofhorroris o...,1901294,NaN,so happy that on too bad has the channel curre...,1901295.0,happy bad channel currently unavailable,unknown,0.649198,False,True,True,False
677,1507289,469820,True,Fri Nov 03 13:28:50 +0000 2017,@115821 is this a scam? I havent set up any pr...,1507288,NaN,is this a scam i havent set up any prime subsc...,1507289.0,scam not set prime subscription,unknown,0.948304,False,True,True,False
4639,2955103,SW_Help,False,Wed Nov 29 18:57:42 +0000 2017,"@307291 Hello, apologies for the delays, I app...",NaN,2955104.0,hello apologies for the delays i appreciate th...,2955104.0,hello apology delay appreciate frustration cau...,unknown,0.691809,False,True,False,True
568,2173068,434794,True,Thu Nov 09 10:19:06 +0000 2017,"@AskLyft hey friends, the temporary authorizat...",2173067,NaN,hey friends the temporary authorization was no...,2173068.0,hey friend temporary authorization refund 15 d...,unknown,0.597290,True,True,True,False
17,1820869,ChipotleTweets,False,Sun Oct 29 00:45:00 +0000 2017,@546646 also Guactober. Sounds like a good tim...,NaN,1820870.0,also guactober sounds like a good time to make...,1820870.0,guactober sound like good time wish shawn,unknown,0.540705,True,True,False,True
2099,926835,339914,True,Fri Oct 13 21:31:53 +0000 2017,@Uber_Support https://t.co/KFz9790iCW,926834,926836.0,NaN,926836.0,NaN,unknown,0.527368,True,True,True,False
2467,2148012,221954,True,Thu Nov 09 07:03:23 +0000 2017,@SW_Help @131778 @121706 I see it as @SW_Help ...,NaN,2148010.0,i see it as explaining why there was congestio...,2148010.0,explain congestion moan,unknown,0.619116,False,True,True,False
2635,2750857,BofA_Help,False,Tue Nov 21 00:40:52 +0000 2017,@603627 Please let us know if you'd like us to...,NaN,2750858.0,please let us know if you d like us to review ...,2750858.0,let know d like review account thank az,unknown,0.472616,True,True,False,True
1096,249608,115990,True,Thu Oct 05 16:07:29 +0000 2017,@175325 Keeping you connected is our goal. We'...,249607,249609.0,keeping you connected is our goal we re here t...,249609.0,keep connect goal find answer start call drop ...,unknown,0.942767,False,True,True,False
2320,402911,162387,True,Mon Oct 09 19:09:29 +0000 2017,@AskeBay @115937 @137680 Anything you need me ...,402909,402912.0,anything you need me to show to reinstate my a...,402912.0,need reinstate account provide,unknown,0.778606,False,True,True,False
366,1383729,130995,True,Sat Oct 28 08:18:28 +0000 2017,@442022 @LondonMidland Put in a claim. I know ...,NaN,1383725.0,put in a claim i know it s not the answer that...,1383725.0,claim know s answer want s way ll,unknown,0.804010,False,True,True,False
4967,2084262,594228,True,Sun Nov 05 23:26:29 +0000 2017,@KeyBank_Help I sent an email on Thursday. As ...,NaN,2084261.0,i sent an email on thursday as of today i have...,2084261.0,send email thursday today response whatsoever,unknown,0.449828,True,True,True,False
3912,2762580,VirginTrains,False,Tue Nov 21 07:39:31 +0000 2017,@772839 @106244 @106245 @106246 Wishing you al...,NaN,2762581.0,wishing you all the best cb,2762581.0,wish good cb,unknown,0.896266,False,True,False,True
892,1140944,AmazonHelp,False,Tue Oct 24 15:47:01 +0000 2017,@388565 ¿Te indicaron alguna explicación del a...,1140945,1140942.0,te indicaron alguna explicaci n del atraso gem...,1140942.0,te indicaron alguna explicaci n del atraso gem...,unknown,0.879728,False,True,False,True
2981,1259271,AskLyft,False,Thu Oct 26 08:58:41 +0000 2017,@415049 Hello! Could you please DM @AskLyft wi...,1259272,1259273.0,hello could you please dm with the phone numbe...,1259273.0,hello dm phone number associate lyft account,unknown,0.593861,True,True,False,True
2222,1633564,499788,True,Tue Oct 17 05:53:04 +0000 2017,@115858 ve @AppleSupport bir günün içinde kaç ...,1633563,NaN,ve bir g n n i inde ka g n var,1633564.0,ve bir g n n inde ka g n var,unknown,0.749382,False,True,True,False
4961,496426,SouthwestAir,False,Fri Dec 01 18:10:59 +0000 2017,@233436 Hi there! Our creamers are lactose-fre...,496427,496428.0,hi there our creamers are lactose free gluten ...,496428.0,hi creamer lactose free gluten free kosher dai...,unknown,0.613503,False,True,False,True
2130,2446503,701357,True,Wed Nov 15 19:37:06 +0000 2017,"@Uber_Support Well, I am trying but even this ...",NaN,2446502.0,well i am trying but even this happen,2446502.0,try happen,unknown,0.580686,True,True,True,False
3819,1272062,164140,True,Thu Oct 26 14:49:44 +0000 2017,@idea_cares When you revert back ?\nThis is co...,1272064,1272061.0,when you revert back this is comes from last 6...,1272061.0,revert come 6 month check issue think,unknown,0.692284,False,True,True,False
3660,1671953,508887,True,Mon Nov 06 04:14:28 +0000 2017,see @115858 came out with new phones and fucki...,1671952,NaN,see came out with new phones and fucking our s...,1671953.0,come new phone fuck shit way you slick,unknown,0.831512,False,True,True,False
1999,1652931,AmazonHelp,False,Mon Nov 06 08:14:00 +0000 2017,@249446 Was it delayed due to a payment issue?...,1652932,1652929.0,was it delayed due to a payment issue at,1652929.0,delay payment issue,unknown,0.608844,False,True,False,True
4688,2670206,airtel_care,False,Sat Nov 18 11:19:44 +0000 2017,"@751989 Hello, apologies on your experience. K...",2670205,2670207.0,hello apologies on your experience kindly prov...,2670207.0,hello apology experience kindly provide affect...,unknown,0.783911,False,True,False,True
1101,2702330,XboxSupport,False,Sun Nov 19 21:13:08 +0000 2017,"@759052 Hello, you can check here on gifting c...",NaN,2702331.0,hello you can check here on gifting content to...,2702331.0,hello check gift content user rm,unknown,0.492430,True,True,False,True
2637,1356859,298731,True,Sun Oct 15 05:27:37 +0000 2017,@129941 Just don't get the app on iOS - 3 badg...,1356857,NaN,just don t get the app on ios 3 badge notifica...,1356859.0,don t app io 3 badge notification t find clear...,unknown,0.463799,True,True,True,False
3690,2398495,Tesco,False,Tue Nov 14 13:21:08 +0000 2017,"@690249 Hello David, apologies for the delay. ...",NaN,2398496.0,hello david apologies for the delay we have an...,2398496.0,hello david apology delay update ll drop dm in...,unknown,0.627373,False,True,False,True
4897,254283,176437,True,Thu Oct 05 18:01:13 +0000 2017,"@SouthwestAir Well, you should definitely keep...",254282,254284.0,well you should definitely keep him around pun...,254284.0,definitely punny people like tough come need g...,unknown,0.925300,False,True,True,False
1286,2404639,691657,True,Tue Nov 14 15:35:16 +0000 2017,@ATVIAssist will do.,NaN,2404636.0,will do,2404636.0,NaN,unknown,0.821971,False,True,True,False
2546,2929327,VerizonSupport,False,Wed Nov 29 06:23:27 +0000 2017,@810372 That's not how we want you to feel. Ho...,"2929328,2929329,2929330,2929331,2929332",2929333.0,that s not how we want you to feel how may we ...,2929333.0,s want feel assist bab,unknown,0.502272,True,True,False,True
2940,545543,XboxSupport,False,Sat Dec 02 16:51:08 +0000 2017,"@246827 Hi there, to check, is this in regards...",NaN,545544.0,hi there to check is this in regards to cod ww...,545544.0,hi check regard cod wwii send photo detailed n...,unknown,0.401273,True,True,False,True
278,1313423,159139,True,Fri Oct 27 10:10:01 +0000 2017,@AmazonHelp There is one left. By the time I g...,1313424,1313422.0,there is one left by the time i get a refund a...,1313422.0,leave time refund order s risky,unknown,0.783501,False,True,True,False
651,2417145,idea_cares,False,Sun Oct 29 11:29:25 +0000 2017,@694638 We request you to please elaborate on ...,NaN,2417143.0,we request you to please elaborate on your con...,2417143.0,request elaborate concern dm idea contact numb...,unknown,0.968622,False,True,False,True
2505,2049345,435537,True,Mon Nov 06 17:39:24 +0000 2017,@VirginAtlantic :( our flight out to San Fran ...,2049343,NaN,our flight out to san fran didn t live up to e...,2049345.0,flight san fran didn t live expectation terrib...,unknown,0.710196,False,True,True,False
4076,2449445,256432,True,Wed Nov 15 03:12:25 +0000 2017,@AmazonHelp Trying to return a faulty item. Wa...,NaN,2449444.0,trying to return a faulty item was promised a ...,2449444.0,try return faulty item promise refund 1 4 hour...,unknown,0.457233,True,True,True,False
1670,389875,AirbnbHelp,False,Mon Oct 09 15:09:31 +0000 2017,"@208300 Hi Mike, we're sorry to hear about thi...",NaN,389876.0,hi mike we re sorry to hear about this experie...,389876.0,hi mike sorry hear experience dm account s ema...,unknown,0.801923,False,True,False,True
2148,513672,238231,True,Fri Dec 01 23:20:19 +0000 2017,I’m seriously considering buying all of my fav...,513670,NaN,i m seriously considering buying all of my fav...,513672.0,m seriously consider buy favorite album cd for...,unknown,0.903055,False,True,True,False
1586,1733300,523524,True,Tue Nov 07 13:03:26 +0000 2017,@ATVIAssist I’m still waiting on my permanent ...,1733302,1733299.0,i m still waiting on my permanent token and do...,1733299.0,m wait permanent token double xp saturday,unknown,0.753415,False,True,True,False
598,2962544,UPSHelp,False,Wed Nov 29 21:24:39 +0000 2017,@394642 Pls DM the tracking numbers and we wou...,NaN,2962543.0,pls dm the tracking numbers and we would be ha...,2962543.0,pls dm tracking number happy check status sp,unknown,0.528629,True,True,False,True
2869,805965,312060,True,Thu Oct 12 14:15:15 +0000 2017,@HPSupport i just installed windows 10 and can...,"805964,805966,805967,805968",NaN,i just installed windows 10 and cannot scan wi...,805965.0,instal window 10 scan wirelessly hp photosmart...,unknown,0.964873,False,True,True,False

### 1.3 : Capture text for analysis (Manual intent check)

In [11]:
df_unlnown_text = df_unknown_sample[['text', 'Clean_text']]
df_unlnown_text

,text,Clean_text
2614,@SpotifyCares Hello. My payment for premium ac...,hello my payment for premium account was succe...
2009,@220140 Kindly DM these details as you are sha...,kindly dm these details as you are sharing sen...
4598,@AmazonHelp Got the same messag from https://t...,got the same messag from please add pakistan i...
1205,@270205 On a real note: Who's going to step up...,on a real note who s going to step up and help...
4023,@TMobileHelp @203665 Plus it looks like ZERO m...,plus it looks like zero mainstream devices sup...
3283,"@141013 Hi, Meg! It sounds like you applied fu...",hi meg it sounds like you applied funds to boo...
1349,@298780 We're happy to check on the status for...,we re happy to check on the status for you ple...
595,@AmazonHelp Si esta todo correcto es vendido y...,si esta todo correcto es vendido y gestionado ...
4339,@500591 No problem!,no problem
1335,"@762342 Apologies for the delay, we are active...",apologies for the delay we are actively workin...
2194,@586340 Thanks for reaching out. What's the ex...,thanks for reaching out what s the exact ios y...
223,@304206 We'll be glad to assist you. Can you p...,we ll be glad to assist you can you please dm ...
406,So happy that #Simpsons #Treehouseofhorroris o...,so happy that on too bad has the channel curre...
677,@115821 is this a scam? I havent set up any pr...,is this a scam i havent set up any prime subsc...
4639,"@307291 Hello, apologies for the delays, I app...",hello apologies for the delays i appreciate th...
568,"@AskLyft hey friends, the temporary authorizat...",hey friends the temporary authorization was no...
17,@546646 also Guactober. Sounds like a good tim...,also guactober sounds like a good time to make...
2099,@Uber_Support https://t.co/KFz9790iCW,NaN
2467,@SW_Help @131778 @121706 I see it as @SW_Help ...,i see it as explaining why there was congestio...
2635,@603627 Please let us know if you'd like us to...,please let us know if you d like us to review ...
1096,@175325 Keeping you connected is our goal. We'...,keeping you connected is our goal we re here t...
2320,@AskeBay @115937 @137680 Anything you need me ...,anything you need me to show to reinstate my a...
366,@442022 @LondonMidland Put in a claim. I know ...,put in a claim i know it s not the answer that...
4967,@KeyBank_Help I sent an email on Thursday. As ...,i sent an email on thursday as of today i have...
3912,@772839 @106244 @106245 @106246 Wishing you al...,wishing you all the best cb
892,@388565 ¿Te indicaron alguna explicación del a...,te indicaron alguna explicaci n del atraso gem...
2981,@415049 Hello! Could you please DM @AskLyft wi...,hello could you please dm with the phone numbe...
2222,@115858 ve @AppleSupport bir günün içinde kaç ...,ve bir g n n i inde ka g n var
4961,@233436 Hi there! Our creamers are lactose-fre...,hi there our creamers are lactose free gluten ...
2130,"@Uber_Support Well, I am trying but even this ...",well i am trying but even this happen
3819,@idea_cares When you revert back ?\nThis is co...,when you revert back this is comes from last 6...
3660,see @115858 came out with new phones and fucki...,see came out with new phones and fucking our s...
1999,@249446 Was it delayed due to a payment issue?...,was it delayed due to a payment issue at
4688,"@751989 Hello, apologies on your experience. K...",hello apologies on your experience kindly prov...
1101,"@759052 Hello, you can check here on gifting c...",hello you can check here on gifting content to...
2637,@129941 Just don't get the app on iOS - 3 badg...,just don t get the app on ios 3 badge notifica...
3690,"@690249 Hello David, apologies for the delay. ...",hello david apologies for the delay we have an...
4897,"@SouthwestAir Well, you should definitely keep...",well you should definitely keep him around pun...
1286,@ATVIAssist will do.,will do
2546,@810372 That's not how we want you to feel. Ho...,that s not how we want you to feel how may we ...
2940,"@246827 Hi there, to check, is this in regards...",hi there to check is this in regards to cod ww...
278,@AmazonHelp There is one left. By the time I g...,there is one left by the time i get a refund a...
651,@694638 We request you to please elaborate on ...,we request you to please elaborate on your con...
2505,@VirginAtlantic :( our flight out to San Fran ...,our flight out to san fran didn t live up to e...
4076,@AmazonHelp Trying to return a faulty item. Wa...,trying to return a faulty item was promised a ...
1670,"@208300 Hi Mike, we're sorry to hear about thi...",hi mike we re sorry to hear about this experie...
2148,I’m seriously considering buying all of my fav...,i m seriously considering buying all of my fav...
1586,@ATVIAssist I’m still waiting on my permanent ...,i m still waiting on my permanent token and do...
598,@394642 Pls DM the tracking numbers and we wou...,pls dm the tracking numbers and we would be ha...
2869,@HPSupport i just installed windows 10 and can...,i just installed windows 10 and cannot scan wi...

### Missing intents in current taxonony:
Createa function to check for missing intent.   
##### Consider the following:
- return_request
- order_cancellation
- fraud_check
- account_access_issue
- technical_issue
- shipping_delay
- general_complaint
- product_support_issue

In [19]:
def set_intent(text):
    if text == "" :
        return "non intent"
    text_l = text.lower()
    if "return" in  text_l or "faulty" in text_l :
        return  'return_request'
    if "scam" in text_l or "fraud" in text_l:
        return "fraud_check"
    if "login" in text_l or "account" in text_l or "reinstate" in text_l:
        return "account_access_issue"
    if "shipping" in text_l or "delay" in text_l or "tracking" in text_l:
        return "shipping_delay"
    if "cannot" in text_l or "not working" in text_l or "installed windows" in text_l:
        return "technical_issue"
    if "delivery" in text_l or "waiting" in text_l or "how long" in text_l:
        return "delivery_status"
    return "unknown_candidate" 

df_unlnown_text["suggested_intent"] = df_unlnown_text["Clean_text"].fillna("").apply(set_intent)
df_unlnown_text[["Clean_text", "suggested_intent"]].head(20)

                                             Clean_text      suggested_intent
2614  hello my payment for premium account was succe...  account_access_issue
2009  kindly dm these details as you are sharing sen...     unknown_candidate
4598  got the same messag from please add pakistan i...        shipping_delay
1205  on a real note who s going to step up and help...     unknown_candidate
4023  plus it looks like zero mainstream devices sup...     unknown_candidate
3283  hi meg it sounds like you applied funds to boo...     unknown_candidate
1349  we re happy to check on the status for you ple...     unknown_candidate
595   si esta todo correcto es vendido y gestionado ...     unknown_candidate
4339                                         no problem     unknown_candidate
1335  apologies for the delay we are actively workin...        shipping_delay
2194  thanks for reaching out what s the exact ios y...     unknown_candidate
223   we ll be glad to assist you can you please dm ...     unknown_candidate
406   so happy that on too bad has the channel curre...     unknown_candidate
677   is this a scam i havent set up any prime subsc...           fraud_check
4639  hello apologies for the delays i appreciate th...        shipping_delay
568   hey friends the temporary authorization was no...     unknown_candidate
17    also guactober sounds like a good time to make...     unknown_candidate
2099                                                NaN            non intent
2467  i see it as explaining why there was congestio...     unknown_candidate
2635  please let us know if you d like us to review ...  account_access_issue

## 2. Overlapping intent analysis:

2.1. Pick pairs that logically overlap

Example:
- billing_issue vs refund_request
- refund_request vs return_request (new)
- general_question vs complaint
- delivery status vs shipping_delay

2.2. Sample and inspect

In [25]:
df_overlap = df[df['intent'].isin(["billing_issue", "refund_request"])].sample(100, random_state=42)
df_overlap[['Clean_text','intent']]

                                             Clean_text          intent
711         ouch what issue are you running into keithm  refund_request
2055  please dm your tracking number and delivery ad...  refund_request
1353  we re here to help george could you please sen...   billing_issue
1064  we take this very seriously please send us a d...  refund_request
656   hey james could you try using a different brow...  refund_request
...                                                 ...             ...
2758  ya he recibido mi funda nueva de para el y es ...  refund_request
2861  quelle a t la r ponse de notre sav une enqu te...  refund_request
2023                unhappy with the quality of product  refund_request
4224  i am sorry for the condition your package arri...   billing_issue
4434  here s the list of the iphone 8 contest winner...  refund_request

[100 rows x 2 columns]

### Analyze if text is more of a billing or refund issue
Example: 
1. i am sorry for the condition your package arri...	billing_issue  
- is more of a refund_request

2.3 Quantify overlap by looking at n‑grams:

In [29]:
from collections import Counter

def top_ngrams(texts, n=2, top_k=20):
    all_ngrams = []
    for t in texts:
        tokens = t.lower().split()
        all_ngrams.extend([" ".join(tokens[i:i+n]) for i in range(len(tokens)-n+1)])
    return Counter(all_ngrams).most_common(top_k)

billing_texts = df[df["intent"] == "billing_issue"]["Clean_text"].dropna().tolist()
refund_texts = df[df["intent"] == "refund_request"]["Clean_text"].dropna().tolist()

top_billing = top_ngrams(billing_texts, n=2)
top_refund = top_ngrams(refund_texts, n=2)
top_billing_refund = pd.DataFrame({'top_billing': top_billing,
                                   'top_refund': top_refund
                                  })
top_billing_refund

         top_billing        top_refund
0       (we can, 42)     (to help, 40)
1          (i m, 38)      (we can, 36)
2         (it s, 37)       (we re, 33)
3      (for the, 36)     (send us, 33)
4   (thanks for, 33)      (if you, 33)
5        (we re, 33)     (for the, 31)
6        (dm us, 31)        (us a, 30)
7      (you can, 28)         (i m, 27)
8    (look into, 28)       (dm us, 25)
9        (don t, 28)        (it s, 25)
10      (if you, 26)     (can you, 24)
11       (i can, 26)      (i have, 24)
12   (thank you, 26)       (i can, 24)
13       (can t, 25)   (please dm, 23)
14        (a dm, 25)       (we ll, 23)
15     (for you, 24)      (let us, 22)
16       (we ll, 24)  (you please, 21)
17      (i have, 23)     (us know, 21)
18        (i am, 22)      (in the, 21)
19      (in the, 22)      (on the, 21)

### overlapping: 
we, can   
i, m  etc

### 3. Recommendations:

**Add new intents**:  
return_request, order_cancellation, fraud_check, account_access_issue, technical_issue, shipping_delay, general_complaint, product_support_issue.

**Refine overlapping intents**:
- Clarify or merge billing_issue and refund_request into payment_issue with sub‑types.
- Separate refund_request (money back) from return_request (item return).

**Use fallback/unknown as training data**:
- Messages currently labeled unknown or falling back should be manually reviewed and used to expand taxonomy and training data.

**Language coverage**: 
- Non‑English messages (Spanish, Turkish) should either be routed to language‑specific models or mapped to intents with multilingual examples.

### 4. Business Insights: as a customer support engineer

**Operational insight:**
- High volume of messages about returns, refunds, and payment issues suggests that post‑purchase flows   
(refunds, cancellations, returns) are a major friction point.

**Product insight:**
- Technical issues around device compatibility and OS upgrades (e.g., Windows 10, iOS app issues) 
indicate gaps in product support documentation or proactive communication.

**Experience insight:**
- Many empathy‑style responses (“sorry for the delay”, “that’s not how we want you to feel”) 
without clear resolution hints at a need for better resolution workflows, not just apology templates.

**Risk insight:**
- Fraud‑related messages (“is this a scam?”) suggest users are confused about legitimate communications—this is a brand trust and security communication issue.